ALTER TABLE QUESTION ALTER COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE QUESTION ALTER COLUMN CREATOR BIGINT;
ALTER TABLE USER ALTER COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE COMMENT ALTER COLUMN COMMENTATOR BIGINT;